I'm sorry, but an uncaught exception occurred.

While running game code:
<<<<<<< HEAD
  File "game/KurumiTokisaki.rpy", line 29, in script
    "[get_txt_patchDB(db_aux_kurumitokisaki_dialogs, 1)]"
IndexError: list index out of range
=======
  File "game/script.rpy", line 93, in script
    $ set_percache("player_name", "player_name","{color=#2786eb}"+name+"{/color}")
  File "game/script.rpy", line 93, in <module>
    $ set_percache("player_name", "player_name","{color=#2786eb}"+name+"{/color}")
TypeError: set_percache() takes 2 positional arguments but 3 were given
>>>>>>> 7c8149ba50f32f02ab7e61bede9ab40ed07d3fa3

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "game/KurumiTokisaki.rpy", line 29, in script
    "[get_txt_patchDB(db_aux_kurumitokisaki_dialogs, 1)]"
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\character.py", line 1440, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
  File "patch_essencials.py", line 10, in get_txt_patchDB
IndexError: list index out of range
=======
  File "game/script.rpy", line 93, in script
    $ set_percache("player_name", "player_name","{color=#2786eb}"+name+"{/color}")
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Python\renpy-8.3.4-sdk\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 93, in <module>
    $ set_percache("player_name", "player_name","{color=#2786eb}"+name+"{/color}")
TypeError: set_percache() takes 2 positional arguments but 3 were given
>>>>>>> 7c8149ba50f32f02ab7e61bede9ab40ed07d3fa3

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.4.24120703
 
<<<<<<< HEAD
Fri Feb  7 19:33:39 2025
=======
Fri Feb  7 22:04:54 2025
>>>>>>> 7c8149ba50f32f02ab7e61bede9ab40ed07d3fa3
